name: release-please
on:
  push:
    branches: [master]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/release-please-action@v1.2.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: "fastify-babel"
